=== vaidikaffle/APIAutomationFramework/src/test/resources/jsonSchema/employeeSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "first_name": {
      "type": "string"
    },
    "last_name": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "jobs": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "marks": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "Hindi": {
              "type": "integer"
            },
            "English": {
              "type": "integer"
            }
          },
          "required": [
            "Hindi",
            "English"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Hindi": {
              "type": "integer"
            },
            "English": {
              "type": "integer"
            }
          },
          "required": [
            "Hindi",
            "English"
          ]
        }
      ]
    },
    "favFoods": {
      "type": "object",
      "properties": {
        "breakfast": {
          "type": "string"
        },
        "lunch": {
          "type": "string"
        },
        "dinner": {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "required": [
        "breakfast",
        "lunch",
        "dinner"
      ]
    }
  },
  "required": [
    "id",
    "first_name",
    "last_name",
    "email",
    "jobs",
    "marks",
    "favFoods"
  ]
}

=== vaidikaffle/APIAutomationFramework/output/postRequestUsingExternalFileResponse.json
{
    "id": "360",
    "first_name": "freddie",
    "last_name": "dooley",
    "email": "shivam@mailinator.com",
    "jobs": [
        "tester",
        "trainer"
    ],
    "marks": [
        {
            "Hindi": 90,
            "English": 80
        },
        {
            "Hindi": 70,
            "English": 60
        }
    ],
    "favFoods": {
        "breakfast": "idly",
        "lunch": "rice",
        "dinner": [
            "chapati",
            "milk"
        ]
    }
}

=== vaidikaffle/APIAutomationFramework/src/test/resources/jsonFiles/request.json
{
  "id": "userID",
  "first_name": "f_name",
  "last_name": "l_name",
  "email": "shivam@mailinator.com",
  "jobs" : ["tester", "trainer"],
  "marks": [
    {
      "Hindi": 90,
      "English": 80
    },
    {
      "Hindi": 70,
      "English": 60
    }
  ],
  "favFoods": {
    "breakfast": "idly",
    "lunch": "rice",
    "dinner": ["chapati", "milk"]
  }
}

=== vaidikaffle/APIAutomationFramework/output/response.json
{
    "id": "851",
    "first_name": "lucienne",
    "last_name": "gleason",
    "email": "shivam@mailinator.com",
    "jobs": [
        "tester",
        "trainer"
    ],
    "marks": [
        {
            "Hindi": 90,
            "English": 80
        },
        {
            "Hindi": 70,
            "English": 60
        }
    ],
    "favFoods": {
        "breakfast": "idly",
        "lunch": "rice",
        "dinner": [
            "chapati",
            "milk"
        ]
    }
}
